spring.application.name=manajementugas
server.port=8081

# Konfigurasi Database H2
spring.datasource.url=jdbc:h2:file:./data/tugasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Sinkronisasi Skema Database otomatis
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
